name: Deploy on New Tag

on:
  push:
    tags:
      - 'v_*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Ensure latest pip
        run: python -m pip install --upgrade pip

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --all-extras

      - name: Build hgraph
        run: poetry build

      - name: Run tests
        run: poetry run pytest

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
